### ISSUE TITLE
Installationsbeschreibung

### ISSUE THREAD

**Issue by maltegwde** [MrFlamez/Wurzelimperium-Bot#1]
Hallo,

könntest du vllt eine kurze Installationsbeschreibung hinzufügen? 
Habe bisher Main.py gestartet, aber weiß nicht wie (und in welcher Reihenfolge) es weiter geht.

Vielen Dank im Voraus

**Comment by cn-ml** [comment]
Ich habe das selbe Problem. Bekomme nur die Meldung:
```
Traceback (most recent call last):
  File "$(PWD)\src\Main.py", line 8, in <module>
    from src.WurzelBot import WurzelBot
ModuleNotFoundError: No module named 'src'
```

**Comment by MrFlamez** [comment]
Ich habe ein Beispiel mit der example.py hochgeladen und auch kleinere Bugfixes vorgenommen. Des Weiteren habe ich noch ein paar Sätze bzgl. der Installation in der Readme hinterlassen. Eine Installation selbst ist gar nicht nötig. Danke für die Rückmeldung.
