### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by westkous** [MrFlamez/Wurzelimperium-Bot#2]
When i try to run the bot, i get a AttributeError. Im a big tecnical noob. I cant fix it. Maybe you can. Will be realy nice.
AttributeError: 'NoneType' object has no attribute 'isProductPlantable'

**Comment by MasterZydra** [comment]
Hello @westkous,
as you can see in the history of this repository, the last change was 7 month ago.

I fixed some errors that occure when using python3 in my fork of this repository.
Here is my repo: https://github.com/MasterZydra/WurzelimperiumBot

Maybe this newer version will already fix your error messages.

**Comment by MrFlamez** [comment]
Hi @westkous 
please use the newer version from @MasterZydra. All further enhancements will be done there. I will update my repository from time to time. I close this issue. if you have still a problem, please create a new issue. thx
